export {Login} from './Login'
export {Registration} from './Registration'
export {Home} from './Home'
export {FullPost} from './FullPost'
export {Subjects} from './Subjects'
export {FullSubject} from './FullSubject'